server:
  port: 9093

bot:
  name: ${TG_BOT_NAME:}
  token: ${TG_BOT_TOKEN:API-key-removed}

logging:
  level:
    ru.neostudy.apiservice: DEBUG
  file:
    name: ./develop/backend/api-service/logs/app.log
    path: logs

storage:
  serverUrl: http://localhost:8081
  save-user-uri: /data-storage/user
  get-user-by-email-uri: /data-storage/user_email/{email}
  get-user-by-telegram-uri: /data-storage/user/{telegramId}
  get-courses-uri: /data-storage/courses
  get-users-without-course-uri: /data-storage/users/without_course
  update-statement-uri: /data-storage/updateStatementStatus
  get-statement-full-info-uri: /statement/{id}
  get-complete-statements: /data-storage/all_getStatements


